### ISSUE TITLE
[request] add modpack database.

### ISSUE THREAD

**Issue by www2000** [NikkyAI/alpacka-meta-files#1]
Is it possible to add an database for minecraft modpacks beside mods?

**Comment by NikkyAI** [comment]
it is possible.. but i will probably not host it
i think modpacks are also accessible via the SOAP api
but i am filtering everything that is not mods in here
https://github.com/NikkyAI/alpacka-meta/blob/master/ProjectFeed.cs#L83-L87

so you could fork and add handling for modpack info, if it makes sense and it is possible to enable / disable with a siimple option or config i will merge a PR

but at the moment i am too busy with the tool i wrote this meta utility for to allocate time for implementing features i am not requiring

PR: although for being able to import curse packs i might add it anyway, no idea when i will get arund to that

**Comment by NikkyAI** [comment]
implemented in NikkyAI/alpacka-meta@703beb0
